# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'calibration_qt5designeryPrYdH.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1350, 850)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 10, 310, 40))
        font = QFont()
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 60, 220, 40))
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QFrame.NoFrame)
        self.label.setWordWrap(True)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(240, 60, 80, 40))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(430, 10, 80, 40))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(340, 60, 170, 40))
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QFrame.NoFrame)
        self.label_2.setWordWrap(True)
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(340, 10, 80, 40))
        self.lineEdit_2.setFont(font)
        self.lineEdit_3 = QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(820, 10, 80, 40))
        self.lineEdit_3.setFont(font)
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(910, 10, 80, 20))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(820, 60, 170, 40))
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setFrameShape(QFrame.NoFrame)
        self.label_3.setWordWrap(True)
        self.listWidget = QListWidget(self.centralwidget)
        QListWidgetItem(self.listWidget)
        QListWidgetItem(self.listWidget)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(530, 10, 120, 40))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(670, 10, 120, 30))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(670, 40, 120, 30))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(670, 70, 120, 30))
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(1010, 10, 130, 40))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(1010, 60, 130, 40))
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setFrameShape(QFrame.NoFrame)
        self.label_4.setWordWrap(True)
        self.lineEdit_4 = QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(1160, 10, 80, 40))
        self.lineEdit_4.setFont(font)
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(1250, 10, 80, 40))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(1160, 60, 170, 40))
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setFrameShape(QFrame.NoFrame)
        self.label_5.setWordWrap(True)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(330, 10, 2, 100))
        self.line.setFrameShadow(QFrame.Plain)
        self.line.setLineWidth(7)
        self.line.setFrameShape(QFrame.VLine)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(520, 10, 2, 100))
        self.line_2.setFrameShadow(QFrame.Plain)
        self.line_2.setLineWidth(7)
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(660, 10, 2, 100))
        self.line_3.setFrameShadow(QFrame.Plain)
        self.line_3.setLineWidth(7)
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(800, 10, 2, 100))
        self.line_4.setFrameShadow(QFrame.Plain)
        self.line_4.setLineWidth(7)
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(1000, 10, 2, 100))
        self.line_5.setFrameShadow(QFrame.Plain)
        self.line_5.setLineWidth(7)
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(1150, 10, 2, 100))
        self.line_6.setFrameShadow(QFrame.Plain)
        self.line_6.setLineWidth(7)
        self.line_6.setFrameShape(QFrame.VLine)
        self.pushButton_9 = QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(530, 60, 120, 20))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(530, 90, 120, 10))
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setFrameShape(QFrame.NoFrame)
        self.label_7.setWordWrap(True)
        self.pushButton_10 = QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(910, 30, 80, 20))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"exp000_202403xx_dorm_calpnphmg", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Enter experiment foldername", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Enter devstring for cam", None))
        self.lineEdit_2.setText(QCoreApplication.translate("MainWindow", u"/dev/video2", None))
        self.lineEdit_3.setText(QCoreApplication.translate("MainWindow", u"(1,3)", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Enter coords for the selected calib pt", None))

        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        ___qlistwidgetitem = self.listWidget.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"ArUco", None));
        ___qlistwidgetitem1 = self.listWidget.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Manual", None));
        self.listWidget.setSortingEnabled(__sortingEnabled)

        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Shoot Frame", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Cancel Frame", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Validate Frame", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Get Homography", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Click above to compute homography matrix", None))
        self.lineEdit_4.setText(QCoreApplication.translate("MainWindow", u"(2,4)", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Enter test point coords, clicking submit will make it appear on the frame", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Mode:", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
    # retranslateUi

